* vterms.el

Associate [[https://github.com/akermu/emacs-libvterm][Vterm]] buffers to regular Emacs buffers.

Quickly recall the matching Vterm buffer after switching buffers or projects.

** Configuration

#+begin_src emacs-lisp :tangle yes
  (use-package vterms
    :bind (("C-c v v" . vterms-toggle)
           ("C-c v z" . vterms-repeat)
           ("C-c v d" . vterms-cd)
           ("C-c v <backspace>" . vterms-back)))
#+end_src

** Usage

*** vterms-toggle

Toggles between a normal buffer and a Vterm buffer associated with it.

Creates associated Vterm buffers as needed.

If the current buffer is in a project, the new Vterm buffer will start in the project's root directory.

Otherwise it will start in the directory where the current buffer's file is located.

*** vterms-back

Unlike ~vterms-toggle~ that closes the current Vterm, this command simply switches to the associated buffer while
leaving the Vterm open.

*** vterms-repeat

Clear the associated Vterm and re-submit the last command to it.

*** vterms-cd

Change the directory of the associated Vterm buffer to the directory of the current buffer.
