* vterms.el

Associate [[https://github.com/akermu/emacs-libvterm][Vterm]] buffers to regular Emacs buffers.

Quickly recall the matching Vterm buffer after switching buffers or projects.

** Configuration

#+begin_src emacs-lisp :tangle yes
  (use-package vterms
    :bind (("C-c v v" . vterms-switch)
           ("C-c v p" . vterms-switch-or-new-in-project-root)
           ("C-c v d" . vterms-switch-or-new)
           ("C-c v z" . vterms-repeat)
           ("C-c v o" . vterms-window))
#+end_src

** Usage

*** vterms-switch

Select a Vterm buffer associated with the current buffer.

Fail if there is no association yet, or the current buffer is itself a Vterm buffer.

*** vterms-new

Create a Vterm buffer associated with the current buffer.

The Vterm buffer will start in the directory where the current buffer's file is located. It will also be named after
this directory.

*** vterms-switch-or-new

Try ~vterms-switch~ falling back on ~vterms-new~.

Specifically if ~vterms-switch~ finds no current association, find a Vterm corresponding to the current buffer's file's
directory and associate it. If no such Vterm is found, create one with ~vterms-new~.

If prefix ARG is given, behave like ~vterms-new~.

*** vterms-new-in-project-root

Create a Vterm buffer associated with the current buffer.

The Vterm buffer will start in the current project's root directory.

*** vterms-switch-or-new-in-project-root

Try ~vterms-switch~ falling back on ~vterms-new-in-project-root~.

Specifically if ~vterms-switch~ finds no current association, find a Vterm corresponding to the current project's root
and associate it. If no such Vterm is found, create one with ~vterms-new-in-project-root~.

If prefix ARG is given, behave like ~vterms-new-in-project-root~.

*** vterms-repeat

Clear a visible Vterm and re-submit the last command to it.

*** vterms-window

Select a Vterm buffer with a currently visible window.
